name: AutoClearLagg
description: Recoded & improved auto clear lagg plugin

main: twisted\autoclearlagg\AutoClearLagg
version: 3.1.0
api: 3.0.0

author: Twisted
fixer: LittleAraaCute (Me:3)
website: https://github.com/TwistedAsylumMC/AutoClearLagg
